menu:
  首页: / || fas fa-home
  分类: /categories/ || fas fa-folder-open
  标签: /tags || fas fa-tags
  归档: /archives/ || fas fa-archive

# code pane
highlight_theme: mac
highlight_copy: true

# 加载动画 Loading Animation
preloader: true

#
social:
  fab fa-github: https://github.com/ATaoyoyo || Github
  fas fa-envelope: mailto:ataoyoyo@foxmail.com || Email

# home top img
top_img: false

# article cover
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:

post_meta:
  page:
    date_type: both # created or updated or both 主页文章日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 主页是否显示标籤
    label: true # true or false 显示描述性文字
  post:
    date_type: both # created or updated or both 文章页日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 文章页是否显示分类
    tags: true # true or false 文章页是否显示标籤
    label: true # true or false 显示描述性文字

toc:
  enable: true
  number: true
  style_simple: true

disable_top_img: true

post_copyright:
  enable: true
  decode: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

post_pagination: false

avatar:
  img: /img/avatar.png
  effect: false # 头像会一直转圈

# copy settings
# copyright: Add the copyright information after copied content (复製的内容后面加上版权信息)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50


translate:
  enable: true
  # 默认按钮显示文字(网站是简体，应设置为'default: 繁')
  default: 简
  #网站默认语言，1: 繁体中文, 2: 简体中文
  defaultEncoding: 1
  #延迟时间,若不在前, 要设定延迟翻译时间, 如100表示100ms,默认为0
  translateDelay: 0
  #当文字是简体时，按钮显示的文字
  msgToTraditionalChinese: "繁"
  #当文字是繁体时，按钮显示的文字
  msgToSimplifiedChinese: "简"

# dark mode
darkmode:
  enable: true
  # dark mode和 light mode切换按钮
  button: true
  autoChangeMode: true

# 阅读模式
readmode: true

# Change font size
change_font_size: true

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# runtimeshow:
  # enable: true
  # publish_date: 6/7/2018 00:00:00  
  ##网页开通时间
  #格式: 月/日/年 时间
  #也可以写成 年/月/日 时间

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    - Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page

sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq  #想要显示的内容

theme_color:
  enable: true
  main: "#F66"
  paginator: "#00c4b6"
  button_hover: "#F66"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
# 图片格式 url(http://xxxxxx.com/xxx.jpg)
# 颜色（HEX值/RGB值/顔色单词/渐变色)
# 留空 不显示背景
background: url(/img/background/bg.jpg)

# footer是否显示图片背景(与top_img一致)
footer_bg: rgba(255, 255, 255, 0.1)

# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖动特效)
  mobile: false

fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# A simple 404 page
error_404:
  enable: true
  subtitle: '頁面沒有找到'
  background: