menu:
  é¦–é¡µ: / || fas fa-home
  åˆ†ç±»: /categories/ || fas fa-folder-open
  å½’æ¡£: /archives/ || fas fa-archive
  å…³äº: /about/ || fas fa-heart

favicon: /img/avatar.png

# code pane
highlight_theme: mac
highlight_copy: true
highlight_shrink: false
code_word_wrap: true

# æ–‡ç« æ˜¾ç¤º
post_meta:
  page:
    date_type: both # created or updated or both ä¸»é¡µæ–‡ç« æ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç±¤
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—
  post:
    date_type: both # created or updated or both æ–‡ç« é¡µæ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç±¤
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—

index_post_content:
  method: 2
  length: 500 # if you set method to 2 or 3, the length need to config

# ä¾§è¾¹æ 
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me!
      link: https://github.com/ATaoyoyo
  card_announcement:
    enable: true
    content: å¤šè¯»ä¹¦ğŸ“–å¤šçœ‹æŠ¥ğŸ“°
      <br />
      77é›¶é£ŸğŸ£å¤šç¡è§‰ğŸ’¤
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 0 # if set 0 will show all
    expand: false # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: YYYYå¹´MMæœˆ # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

# åŠ è½½åŠ¨ç”» Loading Animation
preloader: true

#
social:
  fab fa-github: https://github.com/ATaoyoyo || Github
  fas fa-envelope: mailto:ataoyoyo@foxmail.com || Email

# home top img
top_img: false

# article cover
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:

related_post:
  enable: true
  limit: 6 # æ˜¾ç¤ºæ¨èæ–‡ç« æ•°ç›®
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸæ˜¾ç¤ºåˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥

toc:
  enable: true
  number: true
  style_simple: true

disable_top_img: true

post_copyright:
  enable: true
  decode: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

post_pagination: false

avatar:
  img: /img/avatar.png
  effect: false # å¤´åƒä¼šä¸€ç›´è½¬åœˆ

# copy settings
# copyright: Add the copyright information after copied content (å¤è£½çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

translate:
  enable: true
  # é»˜è®¤æŒ‰é’®æ˜¾ç¤ºæ–‡å­—(ç½‘ç«™æ˜¯ç®€ä½“ï¼Œåº”è®¾ç½®ä¸º'default: ç¹')
  default: ç®€
  #ç½‘ç«™é»˜è®¤è¯­è¨€ï¼Œ1: ç¹ä½“ä¸­æ–‡, 2: ç®€ä½“ä¸­æ–‡
  defaultEncoding: 1
  #å»¶è¿Ÿæ—¶é—´,è‹¥ä¸åœ¨å‰, è¦è®¾å®šå»¶è¿Ÿç¿»è¯‘æ—¶é—´, å¦‚100è¡¨ç¤º100ms,é»˜è®¤ä¸º0
  translateDelay: 0
  #å½“æ–‡å­—æ˜¯ç®€ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToTraditionalChinese: 'ç¹'
  #å½“æ–‡å­—æ˜¯ç¹ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToSimplifiedChinese: 'ç®€'

# dark mode
darkmode:
  enable: true
  # dark modeå’Œ light modeåˆ‡æ¢æŒ‰é’®
  button: true
  autoChangeMode: 2

# é˜…è¯»æ¨¡å¼
readmode: true

# Change font size
change_font_size: true

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# runtimeshow:
# enable: true
# publish_date: 6/7/2018 00:00:00
##ç½‘é¡µå¼€é€šæ—¶é—´
#æ ¼å¼: æœˆ/æ—¥/å¹´ æ—¶é—´
#ä¹Ÿå¯ä»¥å†™æˆ å¹´/æœˆ/æ—¥ æ—¶é—´

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    - Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page

sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq #æƒ³è¦æ˜¾ç¤ºçš„å†…å®¹

theme_color:
  enable: true
  main: '#F66'
  paginator: '#00c4b6'
  button_hover: '#F66'
  text_selection: '#00c4b6'
  link_color: '#99a9bf'
  meta_color: '#858585'
  hr_color: '#A4D8FA'
  code_foreground: '#F47466'
  code_background: 'rgba(27, 31, 35, .05)'
  toc_color: '#00c4b6'
  blockquote_padding_color: '#49b1f5'
  blockquote_background_color: '#49b1f5'
# å›¾ç‰‡æ ¼å¼ url(http://xxxxxx.com/xxx.jpg)
# é¢œè‰²ï¼ˆHEXå€¼/RGBå€¼/é¡”è‰²å•è¯/æ¸å˜è‰²)
# ç•™ç©º ä¸æ˜¾ç¤ºèƒŒæ™¯
background: url(/img/background/bg.jpg)

# footeræ˜¯å¦æ˜¾ç¤ºå›¾ç‰‡èƒŒæ™¯(ä¸top_imgä¸€è‡´)
footer_bg: rgba(255, 255, 255, 0.1)

# Typewriter Effect (æ‰“å­—æ•ˆæœ)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (å†’å…‰ç‰¹æ•ˆ)
  shake: true #  open shake (æŠ–åŠ¨ç‰¹æ•ˆ)
  mobile: false

fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# A simple 404 page
error_404:
  enable: true
  subtitle: 'é¡µé¢æ¶ˆå¤±åœ¨äº†ç¥å¥‡çš„å…ƒå®‡å®™ä¸­...'
  background:

# CDN
# Don't modify the following settings unless you know how they work
# éå¿…è¦è«‹ä¸è¦ä¿®æ”¹
CDN:
  # main
  main_css: /css/index.css
  jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
  main: https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@3.8.4/source/js/main.min.js # /js/main.js
  utils: https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@3.8.4/source/js/utils.min.js # /js/utils.js

  # pjax
  pjax: https://cdn.jsdelivr.net/npm/pjax/pjax.min.js

  # comments
  gitalk: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  gitalk_css: https://cdn.jsdelivr.net/npm/gitalk/dist/gitalk.min.css
  valine: https://cdn.jsdelivr.net/npm/valine/dist/Valine.min.js
  disqusjs: https://cdn.jsdelivr.net/npm/disqusjs@1/dist/disqus.js
  disqusjs_css: https://cdn.jsdelivr.net/npm/disqusjs@1/dist/disqusjs.css
  utterances: https://utteranc.es/client.js
  twikoo: https://cdn.jsdelivr.net/npm/twikoo/dist/twikoo.min.js
  waline: https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js

  # share
  addtoany: https://static.addtoany.com/menu/page.js
  sharejs: https://cdn.jsdelivr.net/npm/social-share.js/dist/js/social-share.min.js
  sharejs_css: https://cdn.jsdelivr.net/npm/social-share.js/dist/css/share.min.css

  # search
  local_search: https://cdn.jsdelivr.net/gh/jerryc127/butterfly.js.org/source/selfjs/localsearch.min.js?ver=3.8.4 # https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@3.8.4/source/js/search/local-search.min.js # /js/search/local-search.js
  algolia_js: https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@3.8.4/source/js/search/algolia.min.js # /js/search/algolia.js
  algolia_search: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.5/dist/instantsearch.min.js
  algolia_search_css: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.5/dist/instantsearch.min.css

  # math
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  katex: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  katex_copytex: https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.js
  katex_copytex_css: https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.css
  mermaid: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

  # count
  busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

  # background effect
  canvas_ribbon: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-ribbon.min.js
  canvas_fluttering_ribbon: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-fluttering-ribbon.min.js
  canvas_nest: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-nest.min.js

  lazyload: https://cdn.jsdelivr.net/npm/vanilla-lazyload/dist/lazyload.iife.min.js
  instantpage: https://cdn.jsdelivr.net/npm/instant.page/instantpage.min.js
  typed: https://cdn.jsdelivr.net/npm/typed.js/lib/typed.min.js
  pangu: https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js

  # photo
  fancybox_css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.css
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
  medium_zoom: https://cdn.jsdelivr.net/npm/medium-zoom/dist/medium-zoom.min.js

  # snackbar
  snackbar_css: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css
  snackbar: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js

  # effect
  activate_power_mode: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/activate-power-mode.min.js
  fireworks: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/fireworks.min.js
  click_heart: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/click-heart.min.js
  ClickShowText: https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/click-show-text.min.js

  # fontawesome
  fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

  # Conversion between Traditional and Simplified Chinese
  translate: https://cdn.jsdelivr.net/gh/jerryc127/butterfly.js.org/source/selfjs/tw_cn.min.js?ver=3.8.4 #https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@3.8.4/source/js/tw_cn.min.js # /js/tw_cn.js

  # justifiedGallery
  justifiedGallery_js: https://cdn.jsdelivr.net/npm/justifiedGallery/dist/js/jquery.justifiedGallery.min.js
  justifiedGallery_css: https://cdn.jsdelivr.net/npm/justifiedGallery/dist/css/justifiedGallery.min.css

  # aplayer
  aplayer_css: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  aplayer_js: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
  meting_js: https://cdn.jsdelivr.net/gh/metowolf/MetingJS@1.2/dist/Meting.min.js

  # Prism.js
  prismjs_js: https://cdn.jsdelivr.net/npm/prismjs/prism.min.js
  prismjs_lineNumber_js: https://cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.min.js
  prismjs_autoloader: https://cdn.jsdelivr.net/npm/prismjs/plugins/autoloader/prism-autoloader.min.js
