menu:
  é¦–é¡µ: / || fas fa-home
  åˆ†ç±»: /categories/ || fas fa-folder-open
  å½’æ¡£: /archives/ || fas fa-archive
  å…³äº: /about/ || fas fa-heart

favicon: /img/avatar.png

# code pane
highlight_theme: mac
highlight_copy: true
highlight_shrink: false
code_word_wrap: true

# æ–‡ç« æ˜¾ç¤º
post_meta:
  post:
    date_type: both # created or updated or both æ–‡ç« é¡µæ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç±¤
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—
  page:
    date_type: created # created or updated or both ä¸»é¡µæ–‡ç« æ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç±¤
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—

# ä¾§è¾¹æ 
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  card_announcement:
    enable: true
    content:
      å¤šè¯»ä¹¦ğŸ“–å¤šçœ‹æŠ¥ğŸ“°
      <br />
      è¦åƒé›¶é£ŸğŸ£å¤šç¡è§‰ğŸ’¤

# åŠ è½½åŠ¨ç”» Loading Animation
preloader: true

#
social:
  fab fa-github: https://github.com/ATaoyoyo || Github
  fas fa-envelope: mailto:ataoyoyo@foxmail.com || Email

# home top img
top_img: false

# article cover
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:

related_post:
  enable: true
  limit: 6 # æ˜¾ç¤ºæ¨èæ–‡ç« æ•°ç›®
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸæ˜¾ç¤ºåˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥

toc:
  enable: true
  number: true
  style_simple: true

disable_top_img: true

post_copyright:
  enable: true
  decode: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

post_pagination: false

avatar:
  img: /img/avatar.png
  effect: false # å¤´åƒä¼šä¸€ç›´è½¬åœˆ

# copy settings
# copyright: Add the copyright information after copied content (å¤è£½çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50


translate:
  enable: true
  # é»˜è®¤æŒ‰é’®æ˜¾ç¤ºæ–‡å­—(ç½‘ç«™æ˜¯ç®€ä½“ï¼Œåº”è®¾ç½®ä¸º'default: ç¹')
  default: ç®€
  #ç½‘ç«™é»˜è®¤è¯­è¨€ï¼Œ1: ç¹ä½“ä¸­æ–‡, 2: ç®€ä½“ä¸­æ–‡
  defaultEncoding: 1
  #å»¶è¿Ÿæ—¶é—´,è‹¥ä¸åœ¨å‰, è¦è®¾å®šå»¶è¿Ÿç¿»è¯‘æ—¶é—´, å¦‚100è¡¨ç¤º100ms,é»˜è®¤ä¸º0
  translateDelay: 0
  #å½“æ–‡å­—æ˜¯ç®€ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToTraditionalChinese: "ç¹"
  #å½“æ–‡å­—æ˜¯ç¹ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToSimplifiedChinese: "ç®€"

# dark mode
darkmode:
  enable: true
  # dark modeå’Œ light modeåˆ‡æ¢æŒ‰é’®
  button: true
  autoChangeMode: 2

# é˜…è¯»æ¨¡å¼
readmode: true

# Change font size
change_font_size: true

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# runtimeshow:
  # enable: true
  # publish_date: 6/7/2018 00:00:00  
  ##ç½‘é¡µå¼€é€šæ—¶é—´
  #æ ¼å¼: æœˆ/æ—¥/å¹´ æ—¶é—´
  #ä¹Ÿå¯ä»¥å†™æˆ å¹´/æœˆ/æ—¥ æ—¶é—´

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    - Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page

sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq  #æƒ³è¦æ˜¾ç¤ºçš„å†…å®¹

theme_color:
  enable: true
  main: "#F66"
  paginator: "#00c4b6"
  button_hover: "#F66"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
# å›¾ç‰‡æ ¼å¼ url(http://xxxxxx.com/xxx.jpg)
# é¢œè‰²ï¼ˆHEXå€¼/RGBå€¼/é¡”è‰²å•è¯/æ¸å˜è‰²)
# ç•™ç©º ä¸æ˜¾ç¤ºèƒŒæ™¯
background: url(/img/background/bg.jpg)

# footeræ˜¯å¦æ˜¾ç¤ºå›¾ç‰‡èƒŒæ™¯(ä¸top_imgä¸€è‡´)
footer_bg: rgba(255, 255, 255, 0.1)

# Typewriter Effect (æ‰“å­—æ•ˆæœ)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (å†’å…‰ç‰¹æ•ˆ)
  shake: true #  open shake (æŠ–åŠ¨ç‰¹æ•ˆ)
  mobile: false

fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# A simple 404 page
error_404:
  enable: true
  subtitle: 'é é¢æ²’æœ‰æ‰¾åˆ°'
  background: